<a href="https://colab.research.google.com/github/SreeHarshaGudise/Python_For_Datascience/blob/Numpy_Basics/Python_HandBook_for_Data_Science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Basic Dynamic Typing

# Basics

In [3]:
num = 10
for i in range(10):
  num += 10
  print("\f Value of i on each iteration ", num)

 Value of i on each iteration  20
 Value of i on each iteration  30
 Value of i on each iteration  40
 Value of i on each iteration  50
 Value of i on each iteration  60
 Value of i on each iteration  70
 Value of i on each iteration  80
 Value of i on each iteration  90
 Value of i on each iteration  100
 Value of i on each iteration  110


In [4]:
x = 4
x = "hi"

In [5]:
# Python List

In [7]:
L = list(range(10))
print(L)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [10]:
type(L[0])

int

In [13]:
L1 = [str(c) for c in L]
print(L1)

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']


In [17]:
L4 = [True, '1', 0.4, 5]
[type(d) for d in L4]

[bool, str, float, int]

# Numpy basics

In [23]:
import numpy as np

L = np.array(L1)
[type(h) for h in L]

# Lists can take multiple types but Numpy Array can only have one type
# and if data comes in different types it tries to upcase the values before converting to array


[numpy.str_,
 numpy.str_,
 numpy.str_,
 numpy.str_,
 numpy.str_,
 numpy.str_,
 numpy.str_,
 numpy.str_,
 numpy.str_,
 numpy.str_]

In [25]:
np.array([3.4, 5, 6, 0])

array([3.4, 5. , 6. , 0. ])

In [28]:
# setting numpy array data type explicityly like below

np.array(['2','3','6'],dtype='float32')

array([2., 3., 6.], dtype=float32)

In [34]:
# to create arrays with zeros
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [35]:
np.ones((4,5), dtype='float32')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)

In [36]:
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [37]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [38]:
np.linspace(1,5, 6)

array([1. , 1.8, 2.6, 3.4, 4.2, 5. ])

In [42]:
np.random.randint(0,10,(3,4)) # Assigning random integers between 0 to 10 repeated and form 3x4 matrix

array([[7, 9, 2, 2],
       [6, 2, 7, 6],
       [3, 1, 9, 7]])

# Attributes of arrays: Determining the size, shape, memory consumption, and data types of arrays
# Indexing of arrays: Getting and setting the value of individual array elements
# Slicing of arrays: Getting and setting smaller subarrays within a larger array
# Reshaping of arrays: Changing the shape of a given array
# Joining and splitting of arrays: Combining multiple arrays into one, and splitting one array into many

In [1]:

import numpy as np
np.random.seed(0)
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3,4,5))

In [2]:
# attributes: dimension, shape, size
print('dimension', x3.ndim)
print('shape', x3.shape)
print('size', x3.size)

dimension 3
shape (3, 4, 5)
size 60


In [3]:
# Array Slicing
# array[start:stop:step]
x1
print(x1)
x1[1::1]

[5 0 3 3 7 9]


array([0, 3, 3, 7, 9])

In [16]:
# Slicing multi dimensional Array
print(x2)
# arr[1:2:1,1:2:1]. first slice is for rows and second slice is for columns
x2[:2,:3] # This gives first two rows and all columns
x2[::,::2] # this gives all rows with columns one after other
x2[::-1, ::-1] # this gives reverse of elements in array


[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

In [21]:
# sub arrays are views instead of copies
print(x2)
x2_sub = x2[:2,:2]
print(x2_sub)
x2_sub[0,0] = 99
print(x2_sub)
print(x2)
print('------------')

# use copy method such that if we change anything in sub array it wont reflect original array
x2_sub_copy = x2[:2,:2].copy()
print(x2_sub_copy)
x2_sub_copy[0,0] = 42
print(x2_sub_copy)
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]
[[99  5]
 [ 7  6]]
[[99  5]
 [ 7  6]]
[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]
------------
[[99  5]
 [ 7  6]]
[[42  5]
 [ 7  6]]
[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [ ]:
#

# Concatenation of Arrays
## concatenate, vstack, hstack


In [24]:
x = np.random.randint(1,10,3)
y = np.random.randint(1,10,3)


In [31]:
z = np.concatenate([x,y]).reshape((2,3))
print(z)


[[5 5 9]
 [5 4 8]]


In [39]:
# vstack is vertical stack and hstack is horizonta stack
x = np.array([[1,2],[2,3]])
print(x)
y = np.vstack([x,[2,5]])
print(y)
z = np.hstack([x,[[99],[99]]])
print(z)

[[1 2]
 [2 3]]
[[1 2]
 [2 3]
 [2 5]]
[[ 1  2 99]
 [ 2  3 99]]
